### ISSUE TITLE
This is awesome

### ISSUE THREAD

**Issue by GRVYDEV** [mycrl/mystery#54]
This is an awesome project! I'm curious though, why not use WebRTC.rs?

**Comment by mycrl** [comment]
> This is an awesome project! I'm curious though, why not use WebRTC.rs?

Mainly I want to write a webrtc server with sfu architecture, so webrtc.rs is not suitable for me, and I want to figure out the technical implementation details of webrtc, so I decided to do the internal implementation myself. It's also a learning process for me.
